media:
    - name: images
      input: content/assets/images/blog
      output: ../../assets/images/blog
      rename: random

content:
    - name: posts
      label: ブログ記事
      type: collection
      path: content/blog
      filename:
          template: "{parimary}/index.md"
          field: create
      fields:
          - name: title
            type: string
            label: タイトル
          - name: description
            type: string
            label: 説明
          - name: date
            type: date
            label: 日時
            options:
                time: true
          - name: tags
            type: object
            list:
                collapsible:
                    collapsed: true
                    summary: "{tag}"

            fields:
                - name: tag
                  label: タグ
                  type: string
          - name: draft
            type: boolean
            label: 下書き
            default: false
          - name: body
            label: 本文
            type: rich-text
            options:
                media: images
                path: "{slug}"
                rename: random
                switcher: true
